# Generated by Django 3.2.8 on 2021-10-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0006_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hood',
            options={'ordering': ['-pk']},
        ),
    ]
